/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package KBTreeUtil;

public class KBTree {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected KBTree(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(KBTree obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        KBTreeUtilJNI.delete_KBTree(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public KBTree(String newickString) {
    this(KBTreeUtilJNI.new_KBTree(newickString), true);
  }

  public long getNodeCount() {
    return KBTreeUtilJNI.KBTree_getNodeCount(swigCPtr, this);
  }

}
