/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package KBTreeUtil;

public class KBTreeUtilJNI {
  public final static native long new_KBTree(String jarg1);
  public final static native void delete_KBTree(long jarg1);
  public final static native long KBTree_getNodeCount(long jarg1, KBTree jarg1_);
}
