#!/bin/bash
#  Simple script which runs the kbase type compiler for us on the tree API spec files.  This file
#  requires that you have checked out the latest type compiler code from one of these repos:
#     (https://bitbucket.org/olson/kb_typecomp/overview) - latest version on mercurial repo
#     (https://git.kbase.us/typecomp.git) - git version on kbase repo, may be out of date
#
#  To use this script, make sure the local paths to the typecomp libs are correctly specified
#  below, then run this script from the directory it is in.
#
#  author:  msneddon
#  created: 5/21/2012

echo "running type_compiler to generate the tree server/client libs..."

# SPECIFY LOCAL TYPE COMPILER PATH HERE
#PATH_TO_TC="/Users/msneddon/Desktop/work/kbase_git/kb_typecomp"
#PATH_TO_TC="/Users/msneddon/Desktop/work/kbase_git/typecomp_from_kbase_git"
PATH_TO_TC="/Users/msneddon/Desktop/trees/git_repo/typecomp"

# Name of type compiler perl executables - this should not have to change
COMPILE_TYPESPEC='/scripts/compile_typespec.pl'
GEN_JAVA_CLIENT='/scripts/gen_java_client.pl'

# Specify input and output locations for the type compiler
OUTPUT_DIR="../lib"
SPEC_FILE="Tree.spec"

PSGI_FILE="Tree.psgi"
SERVICE_MODULE="Bio::KBase::Tree::Service"
CLIENT_MODULE="Bio::KBase::Tree::Client"
JS_NAME="Tree"
PY_NAME="Tree"

# We need to add the type compiler dependencies to the perl path to run
# the type compiler properly
export PERL5LIB="$PATH_TO_TC/lib/";
echo "perl path set to $PERL5LIB"

# more options for the type compiler??  where are these actually documented?
 #            -impl Bio::KBase::CDMI::%sImpl \
 #           -service Bio::KBase::CDMI::Service \
 #          -psgi CDMI.psgi \
 #          -client Bio::KBase::CDMI::Client \
 #          -js CDMI \
 #          -py CDMI \
 #          CDMI-API.spec CDMI-EntityAPI.spec .
 
# actually run the type compiler
RUN_CMD="${PATH_TO_TC}${COMPILE_TYPESPEC} \
            -psgi $PSGI_FILE \
            -service $SERVICE_MODULE \
            -client $CLIENT_MODULE \
            -js $JS_NAME \
            -py $PY_NAME \
            $SPEC_FILE $OUTPUT_DIR"
echo "Running: \"perl ${RUN_CMD}\""
perl $RUN_CMD

# we want to generate java clients, but this code does not
# appear to be fully functional yet ...
#echo "----"
#RUN_CMD="${PATH_TO_TC}${GEN_JAVA_CLIENT} $SPEC_FILE org.kbase.tree $OUTPUT_DIR"
#echo "Running: \"perl ${RUN_CMD}\""
#perl $RUN_CMD

echo "----"
echo "done."


########### DEPRECATED BELOW THIS LINE: THIS CODE CREATED BASIC CALLS FROM XML FILE, BUT THIS IS
########### ACTUALLY DONE IN THE CDMI-API WITH ALL THE OTHER BASIC CDMI-API FUNCTIONS
#
#DB_FILE="ERDB_Model/trees_er.xml"
#COMPILE_DB='/scripts/compile_dbd_to_typespec.pl'
#
# actually run the compiler on the database ???  where is the doc??
# here is an example:
# dbd=/home/parrello/CdmiData/Published/KSaplingDBD.xml
# /home/olson/kb_test/bin/compile_dbd_to_typespec CDMI_API CDMI_EntityAPI $dbd CDMI-EntityAPI.spec  \
#	Bio/KBase/CDMI/CDMI_EntityAPIImpl.pm er_scripts
#"Usage: $0 module-name DBD-xml-file spec-file impl-file\n"
#echo "----"
#RUN_CMD="${PATH_TO_TC}${COMPILE_DB} TreesBasicAPI $DB_FILE TreesBasicAPI.spec $OUTPUT_DIR/TreesBasicAPI_Impl.pm"
#echo "Running: \"perl ${RUN_CMD}\""
#perl $RUN_CMD
# actually run the type compiler
#echo "----"
#RUN_CMD="${PATH_TO_TC}${COMPILE_TYPESPEC} TreesBasicAPI.spec $OUTPUT_DIR"
#echo "Running: \"perl ${RUN_CMD}\""
#perl $RUN_CMD